### ISSUE TITLE
Can't open plugin settings

### ISSUE THREAD

**Issue by StormySky16** [Mopsgamer/BetterDiscord-codes#50]
![image](https://user-images.githubusercontent.com/45293240/188762839-20ec779b-4034-45e4-9f78-dd9cb755cfb5.png)

**Comment by Mopsgamer** [comment]
It is works for me.
Please provide the text of the error.

**Comment by rarksy** [comment]
also having the same issue

**Comment by StormySky16** [comment]
> It is works for me. Please provide the text of the error.

What do you mean text of the error, the error is that "Could not open settings for Animations" toast, that's all.

**Comment by Mopsgamer** [comment]
There should be a set of related errors in the console.

This is probably caused by a broken translation file import.

The console can be opened with ctrl+shift+i and should be enabled in the BetterDiscord settings.

**Comment by rarksy** [comment]
`Error: ENOENT: no such file or directory, open 'C:\Users\rarksy\AppData\Roaming\BetterDiscord\plugins\Animations.translation.json'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.readFileSync (fs.js:377:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
[2022-09-08 03:26:37.343][CONSOLE:ERROR] [Addon Settings] Unable to get settings panel for Animations.

 Cannot read property 'edit' of null
TypeError: Cannot read property 'edit' of null
    at AnimationsPlugin.getSettingsPanel (betterdiscord://plugins/Animations.plugin.js:1375:36)
    at M.showSettings (<anonymous>:4:100482)
    at Object.Ye (https://discord.com/assets/24f44bbb0ea9e92daf07.js:6098:658)
    at qe (https://discord.com/assets/24f44bbb0ea9e92daf07.js:6098:812)
    at https://discord.com/assets/24f44bbb0ea9e92daf07.js:6118:409
    at Pr (https://discord.com/assets/24f44bbb0ea9e92daf07.js:6118:506)
    at Mr (https://discord.com/assets/24f44bbb0ea9e92daf07.js:6118:920)
    at https://discord.com/assets/24f44bbb0ea9e92daf07.js:6124:680
    at ke (https://discord.com/assets/24f44bbb0ea9e92daf07.js:6206:404)
    at https://discord.com/assets/24f44bbb0ea9e92daf07.js:6120:395
    at Br (https://discord.com/assets/24f44bbb0ea9e92daf07.js:6120:425)
    at rn (https://discord.com/assets/24f44bbb0ea9e92daf07.js:6107:757)
    at nn (https://discord.com/assets/24f44bbb0ea9e92daf07.js:6107:7)
    at t.unstable_runWithPriority (https://discord.com/assets/24f44bbb0ea9e92daf07.js:6318:828)
    at Ki (https://discord.com/assets/24f44bbb0ea9e92daf07.js:6129:117)
    at Ue (https://discord.com/assets/24f44bbb0ea9e92daf07.js:6206:144)
    at en (https://discord.com/assets/24f44bbb0ea9e92daf07.js:6106:800)
    at HTMLDivElement.r (https://discord.com/assets/84ea04f75ca3b5ae3788.js:126:559)
[2022-09-08 03:26:38.475][CONSOLE:ERROR] [Animations] Animations ENOENT: no such file or directory, open 'C:\Users\rarksy\AppData\Roaming\BetterDiscord\plugins\Animations.translation.json'`

**Comment by rarksy** [comment]
uninstalling and reinstalling the plugin does not fix either, almost like its just not downloading/importing the required file

**Comment by StormySky16** [comment]
Can confirm, I get basically the same error.
